### ISSUE TITLE
wrong Pyrad version in readthedocs documentation

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#12]
Pyrad version is currently 0.6.6 while in the readthedocs the latest version is marked as 0.6.5:
https://pyrad-mch.readthedocs.io/en/stable/

**Comment by wolfidan** [comment]
I have fixed the version number in the latest doc. But for the stable version, I'm afraid we have to wait until a new version is released. I'll make sure the number is updated then.
