### ISSUE TITLE
Issues in meteoswiss-mdr have not been automatically migrated to MeteoSwiss

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#2]
It would be good to open the issues that where in the old account here :)

**Comment by wolfidan** [comment]
Ciao  @jfigui , unfortunately they cannot be migrated automatically. I will have to do them all manually, but to do this I have to wait until the user of the old account (to which email address I have no access) accepts my invitation to be admin of the new repo.
