### ISSUE TITLE
Improvement of function interpol_field in read_data_radar.py needed

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#26]
The function has difficulties in the transition between 360 and 0 degree so quite often the northernmost pointing ray is left blank.

**Comment by wolfidan** [comment]
I will take a look, @jfigui could you provide an example where this happens please?

**Comment by jfigui** [comment]
Sure, I will send you some test files by email

**Comment by wolfidan** [comment]
Solved in https://github.com/MeteoSwiss/pyrad/releases/tag/v1.6
