### ISSUE TITLE
Able to ingest multiple ODIM polar files containing one parameter of one scan each

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#27]
Previously the ingestion assumed that there was one file with all the parameters per scan.

@wolfidan , can you double check that nothing broke in the process?

**Comment by wolfidan** [comment]
Hi @jfigui 
Do you think you could add some config files and data in https://github.com/MeteoSwiss/pyrad-examples so I could add a CI test that checks the ODIM file reader?

**Comment by wolfidan** [comment]
@jfigui 
Sorry I didn't realize there were already such config files and data on that repo. So I added two unittests in our pyrad CI to check the processing of ODIM files. These tests pass successfully on the dev branch. So I think we are good.
