### ISSUE TITLE
Access to source code of function get_fieldname_pyart from online documentation

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#43]
There is no access to the source code of the function get_fieldname_pyart in: 
https://pyrad-mch.readthedocs.io/en/latest/io.html#pyrad.io.get_fieldname_pyart

This is where the internal Py-ART names are linked to the keywords used in the config files for the fields so this information should be as easily accessible as possible.

**Comment by wolfidan** [comment]
Closing as solved in https://github.com/MeteoSwiss/pyrad/commit/f56403a1b8fa6045854c4113c767c35ec42a78b0
