### ISSUE TITLE
can someone share a script of pyrad using .nc datafile and a video of how to create prdcfg and plot cappi?

### ISSUE THREAD

**Issue by hamidrizvi** [MeteoSwiss/pyrad#5]

**Comment by jfigui** [comment]
Dear @hamidrizvi ,

The easiest way to do that is by creating a Pyrad config file. Have a look at some of the examples of config file in the pyrad-examples repository https://github.com/MeteoSwiss/pyrad-examples/tree/master/config/processing

If I have time next week, I will upload an example reading a C/F Radial file and producing a CAPPI.

Be aware that we are only providing support on a best effort basis.

**Comment by jfigui** [comment]
I am closing this issue since it was addressed in the Pyrad issues
