### ISSUE TITLE
Function _add_dataset broken by change in output type of function _generate_dataset

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#6]
Hi @wolfidan ,
With the addition of gecsx the output of _generate_dataset is a list of new_dataset objects not a new_dataset object.

However the function _add_dataset expects a new_dataset object, not a list so new_dataset cannot be added to the object.

As a patch I pass to the _add_dataset the first object of new_dataset. It is probably not the smartest thing to do but it works for our cases. The first object delivered by gecsx now is the radar object. If you can think of something smarter feel free to propose it.

The drawback of all this is that we will have to make an urgent patch to the pypi and conda packages because as it is it destroys one of the main advantages of using Pyrad (i.e. the consecutive levels of processing).

Greetings from Catalonia!

**Comment by wolfidan** [comment]
Hi @jfigui ,

I'm really sorry to hear that :(. I have created new Pypi and conda packages, which include your fix.
