### ISSUE TITLE
setup options

### ISSUE THREAD

**Issue by waarmond** [MeteoSwiss/pyrad#62]
Grüezi,

having a setup.py or pyproject.toml would be really an improvement. 

https://github.com/meteoswiss-mdr/pyrad/issues/43

**Comment by wolfidan** [comment]
Dear @waarmond ,

The setup.py is here: https://github.com/MeteoSwiss/pyrad/blob/master/src/pyrad_proc/setup.py

**Comment by waarmond** [comment]
Thanks for helping me.
