### ISSUE TITLE
Pylint keeps crashing with Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#7]
From pylint FAQS: https://docs.pylint.org/en/1.6.0/faq.html

Later versions do not mention this issue but could be still present

6.3 Pylint keeps crashing with Maximum recursion depth exceeded

Pylint can crash with this error if you have a string in your analyzed program, created by joining a lot of strings with the addition operator. Due to how Pylint works, visiting nodes on a AST tree and due to how the BinOp node is represented (the node which represents the string ‘1+1’ for instance), the same visit method will be called over and over again, leading to a maximum recursion error. You can alleviate this problem by passing the flag –optimize-ast=y to Pylint. This will activate an optimization which will transform such AST subtrees into the final resulting string. This flag is off by default. If this is not the case, please report a bug!

Other hints:

while waiting the bug are fixed, you may try to rise the value of the python recursion limit.

**Comment by wolfidan** [comment]
Closest as we no longer use pylint in the CI but ruff which is much more efficient and fast.
