### ISSUE TITLE
imp.load_source

### ISSUE THREAD

**Issue by jfigui** [MeteoSwiss/pyrad#8]
read_data_mxpol.py uses imp.load_source which is deprecated since Python 3.4

**Comment by jfigui** [comment]
Here is a discussion on an alternative:
https://github.com/pyinvoke/invoke/issues/214

**Comment by wolfidan** [comment]
I added the following fix which is compatible with the current python 3.X version:
```
import importlib.util
spec = importlib.util.spec_from_file_location("metadata_config", 
                                                  filename)
cfile = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cfile)
```
